var user_items = {
"login": "twhitacre",
"id": 425938,
"avatar_url": "https://avatars.githubusercontent.com/u/425938?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/twhitacre",
"html_url": "https://github.com/twhitacre",
"followers_url": "https://api.github.com/users/twhitacre/followers",
"following_url": "https://api.github.com/users/twhitacre/following{/other_user}",
"gists_url": "https://api.github.com/users/twhitacre/gists{/gist_id}",
"starred_url": "https://api.github.com/users/twhitacre/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/twhitacre/subscriptions",
"organizations_url": "https://api.github.com/users/twhitacre/orgs",
"repos_url": "https://api.github.com/users/twhitacre/repos",
"events_url": "https://api.github.com/users/twhitacre/events{/privacy}",
"received_events_url": "https://api.github.com/users/twhitacre/received_events",
"type": "User",
"site_admin": false,
"name": "Tim Whitacre",
"company": "The Iron Yard",
"blog": "http://timw.co",
"location": "Atlanta, GA",
"email": "tim@timw.co",
"hireable": true,
"bio": null,
"public_repos": 28,
"public_gists": 15,
"followers": 30,
"following": 28,
"created_at": "2010-10-04T03:57:34Z",
"updated_at": "2015-01-26T22:12:56Z"
}